services:
  - type: web
    name: sagar-bijuli
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn electric_shop_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4 