# Generated by Django 4.2.2 on 2025-04-04 02:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_electrician_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrician',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number', max_length=128, null=True, region=None),
        ),
    ]
